baseURL = "/"
languageCode = "en-us"
title = "Mozayc Themes"
theme = "jamstackthemes"
paginate = 30
summaryLength = 10
# enableGitInfo = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  google_analytics_id = ""
  description = "A list of Themes and Starters for JAMstack Sites."
  banner = false
  banner_text = "Announcing the Stackbit Control Center for managing modern websites. 🤙👩🏼‍🎤🔥"
  banner_link = "https://www.stackbit.com/control-center/"
  banner_link_text = "Try It Now"
  [theme_card]
    show_archetype_icons = false
    show_services_icons = false

[taxonomies]
  ssg = "ssg"
  cms = "cms"
  css = "css"
  archetype = "archetype"
  services = "services"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

# Main Menu
[[menu.main]]
	name = "New Themes"
	url = "/"
    weight = 1

[[menu.main]]
	name = "All Themes"
	url = "/themes/"
    weight = 2

