name = "Mozayc Jamstack Alpha Themes"
license = "MIT"
description = "A list of Themes and Starters for MOZAYC-JAMstack Sites."
min_version = 0.51

[author]
  name = "MOZAYC-JAMstack Themes"
  homepage = "https://www.mozayc.io"